CREATE TABLE DENUNCIA_ANEXO (
    ID_ANEXO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_DENUNCIA BIGINT NOT NULL, -- Chave estrangeira para a tabela de denúncias
    NOME_ORIGINAL VARCHAR(255) NOT NULL,
    NOME_FISICO VARCHAR(255) NOT NULL, -- Nome seguro gerado pelo sistema (UUID)
    TIPO_ARQUIVO VARCHAR(50) NOT NULL, -- ex: image/jpeg
    TAMANHO_BYTES BIGINT NOT NULL,
    DATA_UPLOAD TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    CONSTRAINT FK_DENUNCIA FOREIGN KEY (ID_DENUNCIA) REFERENCES DENUNCIA(ID_DENUNCIA)
);